import os
from datetime import datetime
from sqlalchemy import create_engine, Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import declarative_base, relationship, sessionmaker

Base = declarative_base()

class Channel(Base):
    __tablename__ = 'channels'
    id = Column(Integer, primary_key=True)
    username = Column(String(255), unique=True, nullable=False)
    
    videos = relationship("Video", back_populates="channel", cascade="all, delete-orphan")

class Video(Base):
    __tablename__ = 'videos'
    id = Column(Integer, primary_key=True)
    channel_id = Column(Integer, ForeignKey('channels.id'))
    shortcode = Column(String(50), unique=True, nullable=False)
    caption = Column(Text, nullable=True)
    timestamp = Column(DateTime, default=datetime.utcnow)
    local_video_path = Column(String(1024), nullable=True)
    
    channel = relationship("Channel", back_populates="videos")
    frames = relationship("ImageFrame", back_populates="video", cascade="all, delete-orphan")

class ImageFrame(Base):
    __tablename__ = 'image_frames'
    id = Column(Integer, primary_key=True)
    video_id = Column(Integer, ForeignKey('videos.id'))
    local_image_path = Column(String(1024), nullable=False)
    frame_timestamp = Column(Integer, nullable=True) # timestamp in seconds where the frame was extracted
    description = Column(Text, nullable=True) # What the image denotes (could be generated by a VLM, but kept null initially)
    
    video = relationship("Video", back_populates="frames")

def init_db(db_path: str = "instareelrag.db"):
    """Initializes the database and returns a configured sessionmaker."""
    engine = create_engine(f"sqlite:///{db_path}", echo=False)
    Base.metadata.create_all(engine)
    SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    return SessionLocal()

def get_video_stem_by_shortcode(db_session, shortcode: str) -> str:
    """Returns the filename stem (e.g. '2017-02-28_14-00-55_UTC') for a given Instagram shortcode."""
    if not shortcode:
        return None
    try:
        video = db_session.query(Video).filter_by(shortcode=shortcode).first()
        if video and video.local_video_path:
            return os.path.splitext(os.path.basename(video.local_video_path))[0]
    except Exception:
        pass
    return None
